# Generated by Django 3.0.7 on 2020-10-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20201008_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='external_id',
            field=models.BigIntegerField(default=123, editable=False),
            preserve_default=False,
        ),
    ]
