# Generated by Django 3.0.7 on 2020-10-14 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20201013_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='connection',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Connection'),
        ),
    ]
