# Generated by Django 3.0.7 on 2021-01-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20201014_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
