# Generated by Django 3.0.7 on 2020-07-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("A", "Bank account"), ("C", "Cash")],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "external_id",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
            ],
        ),
    ]
