# Generated by Django 3.0.7 on 2020-07-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_auto_20200716_2004"),
    ]

    operations = [
        migrations.RemoveField(model_name="transaction", name="created_at",),
        migrations.RemoveField(model_name="transaction", name="updated_at",),
    ]
