# Generated by Django 3.0.7 on 2020-07-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_auto_20200716_2143"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
